/* Customers */

CREATE TABLE CUSTOMERS(
	id VARCHAR(30) PRIMARY KEY NOT NULL,
	name VARCHAR(40) NOT NULL,
	gender VARCHAR(1) NOT NULL,
	email VARCHAR(100),
	phone VARCHAR(15),
	address VARCHAR(200)
);

/* Login Details */

CREATE TABLE CREDENTIALS(
	id VARCHAR(30) PRIMARY KEY NOT NULL,
	password_hash RAW(16),
	CONSTRAINT fk_CUSTOMERS
		FOREIGN KEY id
		REFERENCES CUSTOMERS(id),
	CONSTRAINT uniq
		UNIQUE (id)
);


/* Accounts */

CREATE TABLE ACCOUNTS(
	id VARCHAR(30) NOT NULL,
	balance NUMBER DEFAULT 0,
	acc_type VARCHAR(10) NOT NULL,
	CONSTRAINT fk_CUSTOMERS
		FOREIGN KEY id
		REFERENCES CUSTOMERS(id),
	CONSTRAINT ck_ACC_TYPE
		CHECK (acc_type in ('REGULAR','CREDIT'))
);

/* Transactions */

CREATE TABLE TRANSACTIONS(
	id VARCHAR(30) NOT NULL,
	ts DATE NOT NULL,
	txn_type VARCHAR(10) NOT NULL
	amount NUMBER NOT NULL,
	CONSTRAINT fk_CUSTOMERS
		FOREIGN KEY id
		REFERENCES CUSTOMERS(id),
	CONSTRAINT ck_TXN_TYPE
		CHECK (txn_type in ('REGULAR','CREDIT','OVERDRAFT'))
);
